version: "3.8"

services:
  cpp_workspace:
    container_name: python.cuda.workspace
    image: python.cuda.workspace.image
    build:
      context: .
      dockerfile: python.cuda.dockerfile
    ports:
      - "3004:22"
      - "7860:7860"
    volumes:
      - python_cuda_workspace_volume:/workspace
    restart: unless-stopped
    command: ["/usr/sbin/sshd", "-D"]
    environment:
      - GIT_SSH_COMMAND=ssh -o StrictHostKeyChecking=no
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  python_cuda_workspace_volume:
