version: "3.8"

services:
  cpp_workspace:
    container_name: cuda.workspace
    image: cuda.workspace.image
    build:
      context: .
      dockerfile: cuda.dockerfile
    ports:
      - "3003:22"
    volumes:
      - cuda_workspace_volume:/workspace
    restart: unless-stopped
    command: ["/usr/sbin/sshd", "-D"]
    environment:
      - GIT_SSH_COMMAND=ssh -o StrictHostKeyChecking=no
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  cuda_workspace_volume:
