Vagrant.configure("2") do |config|
  config.vm.define "docker-ubuntu-cuda-vnc" do |docker_cpp_core|
    docker_cpp_core.vm.provider "docker" do |d|
      d.image = "ubuntu-cuda-vnc"
      d.ports = ["3000:22", "6000:5901"] 
      d.create_args = ["--gpus", "all"]

      # Check if the platform is Windows
      if Vagrant::Util::Platform.windows?
        current_working_directory = Dir.pwd.gsub('\\', '/')
        d.volumes = ["#{current_working_directory}:/workspace"]    
      else
        config.vm.synced_folder '.', '/vagrant', disabled: true
      end        
    end

    docker_cpp_core.ssh.username = "root"
    docker_cpp_core.ssh.private_key_path = ["ssh/vagrant_docker_key"]
    docker_cpp_core.ssh.port = 6000
  end
end
