Vagrant.configure("2") do |config|
  config.vm.define "docker-ubuntu-cuda-vnc" do |docker_cpp_core|
    docker_cpp_core.vm.provider "docker" do |d|
      d.image = "ubuntu-cuda-vnc"
      current_working_directory = Dir.pwd.gsub('\\', '/')
      d.volumes = ["#{current_working_directory}:/workspace"]
      d.ports = ["3000:22", "6000:5901"] 
      d.create_args = ["--gpus", "all"]
    end

    docker_cpp_core.ssh.username = "root"
    docker_cpp_core.ssh.private_key_path = ["ssh/vagrant_docker_key"]
    docker_cpp_core.ssh.port = 6000
  end
end
