Vagrant.configure("2") do |config|
  config.vm.define "docker-cpp-core" do |docker_cpp_core|
    docker_cpp_core.vm.provider "docker" do |d|
      d.image = "cpp-core-latest"
      d.cmd = ["/usr/sbin/sshd", "-D"]
      d.volumes = ["workspace:/workspace"]
      d.ports = ["1002:22"] # Only map port 22 to 1002
    end

    docker_cpp_core.ssh.username = "root"
    docker_cpp_core.ssh.private_key_path = ["ssh/vagrant_docker_key"]
    docker_cpp_core.ssh.port = 1002 # Connect using port 1002
  end
end
