services:
  cpp_workspace:
    build:
      context: ../..
      dockerfile: docker/cpp/Dockerfile
    command:
    - /usr/sbin/sshd
    - -D
    container_name: 2.workspace
    environment:
    - GIT_SSH_COMMAND=ssh -o StrictHostKeyChecking=no
    image: 2.workspace.image
    ports:
    - '40131:22'
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
    - 2_workspace_volume:/workspace
version: '3.8'
volumes:
  2_workspace_volume: {}
